### ISSUE TITLE
Connecting to a database need to render a spinner

### ISSUE THREAD

**Issue by zhaoyi0113** [zhaoyi0113/mongodb-runner#12]

**Comment by happyhardik** [comment]
I have added Mongo configuration to my workspace config, but it's not working any difference to the Mongo Runner list in the left pane. Is this because it's not able to connect to my database and not even showing "Connecting spinner" to me? or something else is wrong? Does it show any messages if it failed to connect after a timeout?

**Comment by zhaoyi0113** [comment]
It should show a success or error message on the right bottom corner.

**Comment by happyhardik** [comment]
Well, then there is a bug!

**Comment by zhaoyi0113** [comment]
Released a new version to include a connection spinner. could you try with that and let me know if it works? If not, could you provide your configurations?

**Comment by zhaoyi0113** [comment]
Fixed in the version 0.6.2.

**Comment by happyhardik** [comment]
It worked, thanks!
