### ISSUE TITLE
SSL with private key instead of password

### ISSUE THREAD

**Issue by matteodisabatino** [zhaoyi0113/mongodb-runner#3]
Is it possible to connect with SSL via private key? And if so, how have I to configure?

**Comment by zhaoyi0113** [comment]
I have released a new version 0.0.6 to support private key connection. Could you try to configure your setting follow this instruction: https://github.com/zhaoyi0113/mongodb-runner#private-key-connection-setting. Since I don't have signed mongodb container, let me know if it doesn't work for you. Also it would be good for me to fix the issue if you can provide your connection options if the new version doesn't work. Thanks.

**Comment by zhaoyi0113** [comment]
fixed in the latest version
